name: Checking Vulnerabilities

on:
    push:
        branches: ['main', 'dev']

jobs:
    security:
        runs-on: ubuntu-latest
        name: Security
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true # To make sure that SARIF upload gets called
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  args: --sarif-file-output=snyk.sarif
            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: snyk.sarif
                  category: synk
