name: Checking Vulnerabilities

on:
    push:
        branches: ['main', 'dev']

jobs:
    security:
        runs-on: ubuntu-latest
        name: Security
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Setup PNPM
              uses: pnpm/action-setup@v3
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm # or npm / yarn
            - name: Install dependencies
              run: pnpm install
            - name: Run Snyk Test to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: test --all-projects --exclude='docs,examples,scripts,node_modules'
            - name: Run Snyk Monitor to check for vulnerabilities
              uses: snyk/actions/node@master
              continue-on-error: true
              env:
                  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                  command: monitor --all-projects --exclude='docs,examples,scripts,node_modules'
